### ISSUE TITLE
No Let's Encrypt Certificate for base domain

### ISSUE THREAD

**Issue by an-mu** [whythawk/full-stack-fastapi-postgresql#43]
Firstly, thank you for publishing this amazing project.

Currently, I am trying to deploy the project to a digital ocean droplet. I can access services like pgadmin, traefik and flower; however, on the base domain, I am missing a let's encrypt certificate (instead I am issued a traefik default cert).

Am I missing a configuration step besides the ones listed in the excellent deployment documentation? Or should the frontend and backend containers be part of the traefik netwok as well?

Thank you.

**Comment by turukawa** [comment]
Hey @an-mu 

Everything needs to be part of the traefik network since the front- and back- are going to be communicating via the API. I'm assuming you followed the guide step-by-step? https://github.com/whythawk/full-stack-fastapi-postgresql/blob/master/docs/deployment-guide.md#traefik-proxy-with-https

**Comment by turukawa** [comment]
If it does break for something I haven't documented, please let me know. Always good to add gotchas to the documentation for future reference. It means we keep improving things. Thanks.
